'\" p
.\" -*- nroff -*-
.TH "ovn-debug" 8 "ovn-debug" "OVN 24\[char46]03\[char46]90" "OVN Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.de SU
.  PP
.  I "\\$1"
..
.PP
.SH "NAME"
.PP
.PP
ovn-debug \- Open Virtual Network debug tool
.SH "SYNOPSIS"
.PP
\fBovn\-debug\fR \fICOMMAND\fR \fI[ARG\[char46]\[char46]\[char46]]\fR
.SH "DESCRIPTION"
.PP
.PP
\fBovn\-debug\fR, OVN debug tool, is a tool to help with debugging of OVN setup\[char46]
.SH "COMMANDS"
.TP
\fBlflow\-stage\-to\-ltable \fISTAGE_NAME\fB\fR
Convert the logical flow stage name e\[char46]g\[char46] \fBls_in_lb\fR into the logical flow table number e\[char46]g\[char46] \fB13\fR\[char46]
.TP
\fBlflow\-stage\-to\-oftable \fISTAGE_NAME\fB\fR
Convert the logical flow stage name e\[char46]g\[char46] \fBls_in_lb\fR into the OpenFlow table number e\[char46]g\[char46] \fB21\fR\[char46]
