'\" p
.\" -*- nroff -*-
.TH "ovn-bridge-controller" 5 " DB Schema 0.0.1" "Open vSwitch 25.09.90" "Open vSwitch Manual"
.fp 5 L CR              \\" Make fixed-width font available as \\fL.
.de TQ
.  br
.  ns
.  TP "\\$1"
..
.de ST
.  PP
.  RS -0.15in
.  I "\\$1"
.  RE
..
.SH NAME
ovn-bridge-controller \- OVN_Bridge_Controller database schema
.PP
.PP
.PP
.PP
This database is the interface between OVN Bridge Controller and the cloud management system (CMS) to program and control the OVS bridges using OVN logical flows\[char46] The CMS produces almost all of the contents of the database\[char46] The \fBovn\-bridge\-controller\fR program monitors the database contents and programs the OVS bridges with the OpenFlow rules\[char46]
.SS "External IDs"
.PP
.PP
Each of the tables in this database contains a special column, named \fBexternal_ids\fR\[char46] This column has the same form and purpose each place it appears\[char46]
.RS
.TP
\fBexternal_ids\fR: map of string-string pairs
Key-value pairs for use by the CMS\[char46] The CMS might use certain pairs, for example, to identify entities in its own configuration that correspond to those in this database\[char46]
.RE
.SH "TABLE SUMMARY"
.PP
The following list summarizes the purpose of each of the tables in the
\fBOVN_Bridge_Controller\fR database.  Each table is described in more detail on a later
page.
.IP "Table" 1in
Purpose
.TQ 1in
\fBBR_Global\fR
Bridge Controller configuration
.TQ 1in
\fBConnection\fR
OVSDB client connections\[char46]
.TQ 1in
\fBSSL\fR
SSL configuration\[char46]
.TQ 1in
\fBBridge\fR
OVS Bridge to control
.TQ 1in
\fBLogical_Flow\fR
Logical flow
.\" check if in troff mode (TTY)
.if t \{
.bp
.SH "TABLE RELATIONSHIPS"
.PP
The following diagram shows the relationship among tables in the
database.  Each node represents a table.  Tables that are part of the
``root set'' are shown with double borders.  Each edge leads from the
table that contains it and points to the table that its value
represents.  Edges are labeled with their column names, followed by a
constraint on the number of allowed values: \fB?\fR for zero or one,
\fB*\fR for zero or more, \fB+\fR for one or more.  Thick lines
represent strong references; thin lines represent weak references.
.RS -1in
.ps -3
.PS
linethick = 1;
linethick = 0.500000;
box at 0.647570,0.625000 wid 1.076400 height 0.500000 "BR_Global"
box at 0.647570,0.625000 wid 1.020844 height 0.444444
linethick = 1.000000;
box at 3.328100,1.000000 wid 1.086800 height 0.500000 "Connection"
linethick = 1.000000;
box at 3.328100,0.250000 wid 0.750000 height 0.500000 "SSL"
linethick = 0.500000;
box at 3.328100,1.750000 wid 0.750000 height 0.500000 "Bridge"
box at 3.328100,1.750000 wid 0.694444 height 0.444444
linethick = 0.500000;
box at 0.647570,1.750000 wid 1.295100 height 0.500000 "Logical_Flow"
box at 0.647570,1.750000 wid 1.239544 height 0.444444
linethick = 1.000000;
spline -> from 1.191900,0.699990 to 1.191900,0.699990 to 1.653100,0.765180 to 2.317900,0.859160 to 2.780200,0.924500
"connections*" at 2.039900,0.988150
linethick = 1.000000;
spline -> from 1.191900,0.550010 to 1.191900,0.550010 to 1.712000,0.476490 to 2.491300,0.366330 to 2.946700,0.301960
"ssl?" at 2.039900,0.591960
linethick = 1.000000;
spline -> from 1.296900,1.750000 to 1.296900,1.750000 to 1.813400,1.750000 to 2.524000,1.750000 to 2.949300,1.750000
"bridge?" at 2.039900,1.849000
.ps +3
.PE
.RE\}
.bp
.SH "BR_Global TABLE"
.PP
.SS "Summary:
.TQ 3.00in
\fBbr_cfg\fR
integer
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.TQ .25in
\fICommon options:\fR
.RS .25in
.TQ 2.75in
\fBoptions\fR
map of string-string pairs
.RE
.TQ .25in
\fIConnection Options:\fR
.RS .25in
.TQ 2.75in
\fBconnections\fR
set of \fBConnection\fRs
.TQ 2.75in
\fBssl\fR
optional \fBSSL\fR
.RE
.SS "Details:
.IP "\fBbr_cfg\fR: integer"
Sequence number for client to increment\[char46] When a client modifies any part of the bridge Controller database configuration and wishes to wait for \fBovn\-br\-controller\fR to finish applying the changes, it may increment this sequence number\[char46]
.ST "Common Columns:"
.PP
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.ST "Common options:"
.PP
.IP "\fBoptions\fR: map of string-string pairs"
This column provides general key/value settings\[char46] The supported options are described individually below\[char46]
.ST "Connection Options:"
.PP
.IP "\fBconnections\fR: set of \fBConnection\fRs"
Database clients to which the Open vSwitch database server should connect or on which it should listen, along with options for how these connections should be configured\[char46] See the \fBConnection\fR table for more information\[char46]
.IP "\fBssl\fR: optional \fBSSL\fR"
Global SSL/TLS configuration\[char46]
.bp
.SH "Connection TABLE"
.PP
.PP
.PP
Configuration for a database connection to an Open vSwitch database (OVSDB) client\[char46]
.PP
.PP
This table primarily configures the Open vSwitch database server (\fBovsdb\-server\fR)\[char46]
.PP
.PP
The Open vSwitch database server can initiate and maintain active connections to remote clients\[char46] It can also listen for database connections\[char46]
.SS "Summary:
.TQ .25in
\fICore Features:\fR
.RS .25in
.TQ 2.75in
\fBtarget\fR
string (must be unique within table)
.RE
.TQ .25in
\fIClient Failure Detection and Handling:\fR
.RS .25in
.TQ 2.75in
\fBmax_backoff\fR
optional integer, at least 1,000
.TQ 2.75in
\fBinactivity_probe\fR
optional integer
.RE
.TQ .25in
\fIStatus:\fR
.RS .25in
.TQ 2.75in
\fBis_connected\fR
boolean
.TQ 2.75in
\fBstatus : last_error\fR
optional string
.TQ 2.75in
\fBstatus : state\fR
optional string, one of \fBACTIVE\fR, \fBBACKOFF\fR, \fBCONNECTING\fR, \fBIDLE\fR, or \fBVOID\fR
.TQ 2.75in
\fBstatus : sec_since_connect\fR
optional string, containing an integer, at least 0
.TQ 2.75in
\fBstatus : sec_since_disconnect\fR
optional string, containing an integer, at least 0
.TQ 2.75in
\fBstatus : locks_held\fR
optional string
.TQ 2.75in
\fBstatus : locks_waiting\fR
optional string
.TQ 2.75in
\fBstatus : locks_lost\fR
optional string
.TQ 2.75in
\fBstatus : n_connections\fR
optional string, containing an integer, at least 2
.TQ 2.75in
\fBstatus : bound_port\fR
optional string, containing an integer
.RE
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.TQ 2.75in
\fBother_config\fR
map of string-string pairs
.RE
.SS "Details:
.ST "Core Features:"
.PP
.IP "\fBtarget\fR: string (must be unique within table)"
Connection methods for clients\[char46]
.IP
The following connection methods are currently supported:
.RS
.TP
\fBssl:\fIhost\fB\fR[\fB:\fIport\fB\fR]
The specified SSL/TLS \fIport\fR on the host at the given \fIhost\fR, which can either be a DNS name (if built with unbound library) or an IP address\[char46] A valid SSL/TLS configuration must be provided when this form is used, this configuration can be specified via command-line options or the \fBSSL\fR table\[char46]
.IP
If \fIport\fR is not specified, it defaults to 6640\[char46]
.IP
SSL/TLS support is an optional feature that is not always built as part of OVN or Open vSwitch\[char46]
.TP
\fBtcp:\fIhost\fB\fR[\fB:\fIport\fB\fR]
The specified TCP \fIport\fR on the host at the given \fIhost\fR, which can either be a DNS name (if built with unbound library) or an IP address\[char46] If \fIhost\fR is an IPv6 address, wrap it in square brackets, e\[char46]g\[char46] \fBtcp:[::1]:6640\fR\[char46]
.IP
If \fIport\fR is not specified, it defaults to 6640\[char46]
.TP
\fBpssl:\fR[\fIport\fR][\fB:\fIhost\fB\fR]
Listens for SSL/TLS connections on the specified TCP \fIport\fR\[char46] Specify 0 for \fIport\fR to have the kernel automatically choose an available port\[char46] If \fIhost\fR, which can either be a DNS name (if built with unbound library) or an IP address, is specified, then connections are restricted to the resolved or specified local IPaddress (either IPv4 or IPv6 address)\[char46] If \fIhost\fR is an IPv6 address, wrap in square brackets, e\[char46]g\[char46] \fBpssl:6640:[::1]\fR\[char46] If \fIhost\fR is not specified then it listens only on IPv4 (but not IPv6) addresses\[char46] A valid SSL/TLS configuration must be provided when this form is used, this can be specified either via command-line options or the \fBSSL\fR table\[char46]
.IP
If \fIport\fR is not specified, it defaults to 6640\[char46]
.IP
SSL/TLS support is an optional feature that is not always built as part of OVN or Open vSwitch\[char46]
.TP
\fBptcp:\fR[\fIport\fR][\fB:\fIhost\fB\fR]
Listens for connections on the specified TCP \fIport\fR\[char46] Specify 0 for \fIport\fR to have the kernel automatically choose an available port\[char46] If \fIhost\fR, which can either be a DNS name (if built with unbound library) or an IP address, is specified, then connections are restricted to the resolved or specified local IP address (either IPv4 or IPv6 address)\[char46] If \fIhost\fR is an IPv6 address, wrap it in square brackets, e\[char46]g\[char46] \fBptcp:6640:[::1]\fR\[char46] If \fIhost\fR is not specified then it listens only on IPv4 addresses\[char46]
.IP
If \fIport\fR is not specified, it defaults to 6640\[char46]
.RE
.IP
When multiple clients are configured, the \fBtarget\fR values must be unique\[char46] Duplicate \fBtarget\fR values yield unspecified results\[char46]
.ST "Client Failure Detection and Handling:"
.PP
.IP "\fBmax_backoff\fR: optional integer, at least 1,000"
Maximum number of milliseconds to wait between connection attempts\[char46] Default is implementation-specific\[char46]
.IP "\fBinactivity_probe\fR: optional integer"
Maximum number of milliseconds of idle time on connection to the client before sending an inactivity probe message\[char46] If Open vSwitch does not communicate with the client for the specified number of seconds, it will send a probe\[char46] If a response is not received for the same additional amount of time, Open vSwitch assumes the connection has been broken and attempts to reconnect\[char46] Default is implementation-specific\[char46] A value of 0 disables inactivity probes\[char46]
.ST "Status:"
.PP
.PP
.PP
Key-value pair of \fBis_connected\fR is always updated\[char46] Other key-value pairs in the status columns may be updated depends on the \fBtarget\fR type\[char46]
.PP
.PP
When \fBtarget\fR specifies a connection method that listens for inbound connections (e\[char46]g\[char46] \fBptcp:\fR or \fBpunix:\fR), both \fBn_connections\fR and \fBis_connected\fR may also be updated while the remaining key-value pairs are omitted\[char46]
.PP
.PP
On the other hand, when \fBtarget\fR specifies an outbound connection, all key-value pairs may be updated, except the above-mentioned two key-value pairs associated with inbound connection targets\[char46] They are omitted\[char46]
.IP "\fBis_connected\fR: boolean"
\fBtrue\fR if currently connected to this client, \fBfalse\fR otherwise\[char46]
.IP "\fBstatus : last_error\fR: optional string"
A human-readable description of the last error on the connection to the manager; i\[char46]e\[char46] \fBstrerror(errno)\fR\[char46] This key will exist only if an error has occurred\[char46]
.IP "\fBstatus : state\fR: optional string, one of \fBACTIVE\fR, \fBBACKOFF\fR, \fBCONNECTING\fR, \fBIDLE\fR, or \fBVOID\fR"
The state of the connection to the manager:
.RS
.TP
\fBVOID\fR
Connection is disabled\[char46]
.TP
\fBBACKOFF\fR
Attempting to reconnect at an increasing period\[char46]
.TP
\fBCONNECTING\fR
Attempting to connect\[char46]
.TP
\fBACTIVE\fR
Connected, remote host responsive\[char46]
.TP
\fBIDLE\fR
Connection is idle\[char46] Waiting for response to keep-alive\[char46]
.RE
.IP
These values may change in the future\[char46] They are provided only for human consumption\[char46]
.IP "\fBstatus : sec_since_connect\fR: optional string, containing an integer, at least 0"
The amount of time since this client last successfully connected to the database (in seconds)\[char46] Value is empty if client has never successfully been connected\[char46]
.IP "\fBstatus : sec_since_disconnect\fR: optional string, containing an integer, at least 0"
The amount of time since this client last disconnected from the database (in seconds)\[char46] Value is empty if client has never disconnected\[char46]
.IP "\fBstatus : locks_held\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection holds\[char46] Omitted if the connection does not hold any locks\[char46]
.IP "\fBstatus : locks_waiting\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection is currently waiting to acquire\[char46] Omitted if the connection is not waiting for any locks\[char46]
.IP "\fBstatus : locks_lost\fR: optional string"
Space-separated list of the names of OVSDB locks that the connection has had stolen by another OVSDB client\[char46] Omitted if no locks have been stolen from this connection\[char46]
.IP "\fBstatus : n_connections\fR: optional string, containing an integer, at least 2"
When \fBtarget\fR specifies a connection method that listens for inbound connections (e\[char46]g\[char46] \fBptcp:\fR or \fBpssl:\fR) and more than one connection is actually active, the value is the number of active connections\[char46] Otherwise, this key-value pair is omitted\[char46]
.IP "\fBstatus : bound_port\fR: optional string, containing an integer"
When \fBtarget\fR is \fBptcp:\fR or \fBpssl:\fR, this is the TCP port on which the OVSDB server is listening\[char46] (This is particularly useful when \fBtarget\fR specifies a port of 0, allowing the kernel to choose any available port\[char46])
.ST "Common Columns:"
.PP
The overall purpose of these columns is described under \fBCommon
Columns\fR at the beginning of this document\[char46]
.IP "\fBexternal_ids\fR: map of string-string pairs"
.IP "\fBother_config\fR: map of string-string pairs"
.bp
.SH "SSL TABLE"
.PP
SSL/TLS configuration for ovn-nb database access\[char46]
.SS "Summary:
.TQ 3.00in
\fBprivate_key\fR
string
.TQ 3.00in
\fBcertificate\fR
string
.TQ 3.00in
\fBca_cert\fR
string
.TQ 3.00in
\fBbootstrap_ca_cert\fR
boolean
.TQ 3.00in
\fBssl_protocols\fR
string
.TQ 3.00in
\fBssl_ciphers\fR
string
.TQ 3.00in
\fBssl_ciphersuites\fR
string
.TQ .25in
\fICommon Columns:\fR
.RS .25in
.TQ 2.75in
\fBexternal_ids\fR
map of string-string pairs
.RE
.SS "Details:
.IP "\fBprivate_key\fR: string"
Name of a PEM file containing the private key used as the switch\(cqs identity for SSL/TLS connections to the controller\[char46]
.IP "\fBcertificate\fR: string"
Name of a PEM file containing a certificate, signed by the certificate authority (CA) used by the controller and manager, that certifies the switch\(cqs private key, identifying a trustworthy switch\[char46]
.IP "\fBca_cert\fR: string"
Name of a PEM file containing the CA certificate used to verify that the switch is connected to a trustworthy controller\[char46]
.IP "\fBbootstrap_ca_cert\fR: boolean"
If set to \fBtrue\fR, then Open vSwitch will attempt to obtain the CA certificate from the controller on its first SSL/TLS connection and save it to the named PEM file\[char46] If it is successful, it will immediately drop the connection and reconnect, and from then on all SSL/TLS connections must be authenticated by a certificate signed by the CA certificate thus obtained\[char46] \fBThis option exposes the
SSL/TLS connection to a man\-in\-the\-middle attack obtaining the initial
CA certificate\[char46]\fR It may still be useful for bootstrapping\[char46]
.IP "\fBssl_protocols\fR: string"
Range or a comma- or space-delimited list of the SSL/TLS protocols to enable for SSL/TLS connections\[char46]
.IP
Supported protocols include \fBTLSv1\[char46]2\fR and \fBTLSv1\[char46]3\fR\[char46] Ranges can be provided in a form of two protocol names separated with a dash (\fBTLSv1\[char46]2\-TLSv1\[char46]3\fR), or as a single protocol name with a plus sign (\fBTLSv1\[char46]2+\fR)\[char46] The value can be a list of protocols or exactly one range\[char46] The range is a preferred way of specifying protocols and the configuration always behaves as if the range between the minimum and the maximum specified version is provided, i\[char46]e\[char46], if the value is set to \fBTLSv1\[char46]X,TLSv1\[char46](X+2)\fR, the \fBTLSv1\[char46](X+1)\fR will also be enabled as if it was a range\[char46] Regardless of order, the highest protocol supported by both sides will be chosen when making the connection\[char46]
.IP
The default when this option is omitted is \fBTLSv1\[char46]2+\fR\[char46]
.IP "\fBssl_ciphers\fR: string"
List of ciphers (in OpenSSL cipher string format) to be supported for SSL/TLS connections with TLSv1\[char46]2\[char46] The default when this option is omitted is \fBDEFAULT:@SECLEVEL=2\fR\[char46]
.IP "\fBssl_ciphersuites\fR: string"
List of ciphersuites (in OpenSSL ciphersuites string format) to be supported for SSL/TLS connections with TLSv1\[char46]3 and later\[char46] Default value from OpenSSL will be used when this option is omitted\[char46]
.ST "Common Columns:"
.PP
The overall purpose of these columns is described under \fBCommon
Columns\fR at the beginning of this document\[char46]
.IP "\fBexternal_ids\fR: map of string-string pairs"
.bp
.SH "Bridge TABLE"
.PP
.SS "Summary:
.TQ 3.00in
\fBname\fR
string (must be unique within table)
.TQ 3.00in
\fBoptions\fR
map of string-string pairs
.TQ 3.00in
\fBexternal_ids\fR
map of string-string pairs
.SS "Details:
.IP "\fBname\fR: string (must be unique within table)"
Name of the OVS bridge\[char46] This bridge should exist in the local OVS database\[char46]
.IP "\fBoptions\fR: map of string-string pairs"
Reserved for future use\[char46]
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
.bp
.SH "Logical_Flow TABLE"
.PP
.SS "Summary:
.TQ 3.00in
\fBbridge\fR
optional \fBBridge\fR
.TQ 3.00in
\fBtable_id\fR
integer, in range 0 to 100
.TQ 3.00in
\fBpriority\fR
integer, in range 0 to 65,535
.TQ 3.00in
\fBmatch\fR
string
.TQ 3.00in
\fBactions\fR
string
.TQ 3.00in
\fBexternal_ids\fR
map of string-string pairs
.SS "Details:
.IP "\fBbridge\fR: optional \fBBridge\fR"
The bridge to which the logical flow belongs to\[char46]
.IP "\fBtable_id\fR: integer, in range 0 to 100"
The stage in the logical pipeline, analogous to an OpenFlow table number\[char46]
.IP "\fBpriority\fR: integer, in range 0 to 65,535"
The flow\(cqs priority\[char46] Flows with numerically higher priority take precedence over those with lower\[char46] If two logical flows with the same priority both match, then the one actually applied to the packet is undefined\[char46]
.IP "\fBmatch\fR: string"
A matching expression\[char46] OVN provides a superset of OpenFlow matching capabilities, using a syntax similar to Boolean expressions in a programming language\[char46]
.IP
Please see the documentation of the \fBmatch\fR column of the \fBLogical_Flow\fR table in the \fBOVN_Southbound\fR database\[char46]
.IP "\fBactions\fR: string"
Logical datapath actions, to be executed when the logical flow represented by this row is the highest-priority match\[char46]
.IP
Actions share lexical syntax with the \fBmatch\fR column\[char46] An empty set of actions (or one that contains just white space or comments), or a set of actions that consists of just \fBdrop;\fR, causes the matched packets to be dropped\[char46] Otherwise, the column should contain a sequence of actions, each terminated by a semicolon\[char46]
.IP
Please see the documentation of the \fBactions\fR column of the \fBLogical_Flow\fR table in the \fBOVN_Southbound\fR database\[char46]
.IP
While \fBovn\-br\-controller\fR technically supports all OVN logical flow actions defined in the \fBactions\fR column of the \fBLogical_Flow\fR table in the \fBOVN_Southbound\fR, some actions are not intended for use by the CMS\[char46] These include controller OpenFlow actions (e\[char46]g\[char46], put_dhcp_opts, dns_lookup) and OVN-specific actions (e\[char46]g\[char46], look_arp, look_fdb)\[char46]
.IP
It is the CMS\(cqs responsibility to avoid using such actions\[char46] When the CMS defines the packet pipeline in the OVS bridge and adds logical flows using \fBovn\-br\-controller\fR, it is expected to be mindful of using only relevant OVN actions\[char46]
.IP "\fBexternal_ids\fR: map of string-string pairs"
See \fBExternal IDs\fR at the beginning of this document\[char46]
